config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }
  resource :customer, only: [:edit, :update] do
    patch 'update_addresses'
  end

  root 'books#bestsellers'
  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  resources :categories, only: [:index, :show]
  resources :authors, only: [:show]

  resource :cart, only: [:show, :update] do
    post    'add_item'
    delete  'remove_item'
    post    'checkout'
    delete  'clear'
  end

  resources :orders, only: [:index, :show] do
    resource :checkout, only: [:show] do
      get   'addresses'
      patch 'update_addresses'
      get   'delivery'
      patch 'update_delivery'
      get   'payment'
      patch 'update_payment'
      get   'confirm'
      post  'place'
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM
  belongs_to :customer
  belongs_to :delivery
  has_many :order_items
  has_one :credit_card
  has_one :billing_address
  has_one :shipping_address

  validates :total_price, :completed_date, :state, presence: true

  aasm column: :state do
    state :in_progress, initial: true
    state :in_queue
    state :in_delivery
    state :delivered
    state :canceled

    event :place, before: :place_order do
      transitions from: :in_progress, to: :in_queue
    end

    event :processed do
      transitions from: :in_queue, to: :in_delivery
    end

    event :delivered do
      transitions from: :in_delivery, to: :delivered
    end

    event :cancel do
      transitions from: [:in_queue, :in_delivery], to: :canceled
    end
  end

  def state_enum
    ['in_queue', 'in_delivery', 'delivered', 'canceled']
  end

  def place_order
    if self.total_price && self.delivery.price
      self.completed_date = Time.now
      self.total_price += self.delivery.price
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_customer
  load_and_authorize_resource
  def index
  end

  def show
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/addresses.html.haml
.container
  .row
  = simple_form_for(:addresses, url: order_create_addresses_path, :method => :put) do |a|
    .col-md-4
      .panel.panel-default
        .panel-heading
          %h4= t('settings.billing_address', :default => "Billing Address")
        .panel-body
          = simple_fields_for @billing_address do |ba|
            = ba.input :firstname
            = ba.input :lastname
            = ba.input :address
            = ba.input :city
            = ba.input :country_id, collection: @countries
            = ba.input :zipcode
            = ba.input :phone
    .col-md-4
      .panel.panel-default
        .panel-heading
          %h4= t('settings.shippin_address', :default => "Shipping Address")
        .panel-body
          = simple_fields_for @shipping_address do |sa|
            = sa.input :firstname
            = sa.input :lastname
            = sa.input :address
            = sa.input :city
            = sa.input :country_id, collection: @countries
            = sa.input :zipcode
            = sa.input :phone
    .col-md-4
    .col-md-12
      = a.submit t("orders.save")

app/views/orders/confirm.html.haml
.container
  .row
    .col-md-12
      %h4 CONFIRM
    .col-md-3
      %h5
        Billing Address
        = link_to('edit', order_addresses_path)
      %p= "#{@order.billing_address.firstname} #{@order.billing_address.lastname}"
      %p="#{@order.billing_address.address}"
      %p="#{@order.billing_address.city} #{@order.billing_address.zipcode}"
      %p="#{@order.billing_address.country.name}"
      %p="#{@order.billing_address.phone}"
    .col-md-3
      %h5 Shipping Address
      %br= @order.shipping_address
    .col-md-3
      %h5 Shipments
      %br= @order.delivery
    .col-md-3
      %h5 Payment Information
      %br= @order.credit_card.number
      = "#{@order.credit_card.expiration_month} / #{@order.credit_card.expiration_year}"
    .col-md-12
      = @order.order_items.map(&:book).map(&:title)
    .col-md-12
      %br= button_to 'PLACE ORDER', order_place_path, method: :post

app/views/orders/delivery.html.haml
.container
  .row
    .col-md-4
      = simple_form_for @order, url: order_update_delivery_path(@order), method: :patch do |f|
        - @deliveries.each do |d|
          .radio
          = f.radio_button :delivery_id, d.id, checked: d == @order.delivery || d == @deliveries.first
          = "#{d.title} + #{number_to_currency(d.price)}"
        %br= f.submit t("orders.save")
    .col-md-4
    .col-md-4

app/views/orders/index.html.haml
.container
  .row
    .col-md-12
    %h4
      %b= t('orders.in_progress')
    - @orders.in_progress.each do |o|
      %table.table.table-hover
        %thead
          %tr
            %th
            %th= t('orders.book')
            %th.text-center= t('orders.price')
            %th.text-center= t('orders.qty')
            %th.text-center= t('orders.total')
            %th
        - o.order_items.each do |oi|
          %tr
            %td= image_tag(oi.book.book_cover, size: "50x82")
            %td
              %dl
                %dt= oi.book.title
                %dd= truncate(oi.book.description, length: 250)
            %td.text-center= number_to_currency oi.price / oi.quantity
            %td.text-center= oi.quantity
            %td.text-center= number_to_currency oi.price
      %ul.list-unstyled.list-inline
        %li= link_to t('orders.back_to_checkout'), order_checkout_path(o), class: 'btn btn-success'
        %li.pull-right
          %ins= "#{t('orders.subtotal')} #{number_to_currency o.total_price}"
%br
.container
  .row
    .col-md-12
    %h4
      = t('orders.waiting_for_processing')
    %table.table.table-hover
      %thead
        %tr
          %th.text-center= t('orders.number')
          %th.text-center= t('orders.completed_at')
          %th.text-center= t('orders.total')
          %th
      - @orders.in_queue.each do |o|
        %tr.text-center
          %td= "№#{o.id}"
          %td= o.completed_date.strftime('%Y-%m-%d')
          %td= number_to_currency o.total_price
          %td= link_to t('orders.view'), order_path(o)
%br
.container
  .row
    .col-md-12
    %h4
      = t('orders.in_delivery')
    %table.table.table-hover
      %thead
        %tr
          %th.text-center= t('orders.number')
          %th.text-center= t('orders.completed_at')
          %th.text-center= t('orders.total')
          %th
      - @orders.in_delivery.each do |o|
        %tr.text-center
          %td= "№#{o.id}"
          %td= o.completed_date.strftime('%Y-%m-%d')
          %td= number_to_currency o.total_price
          %td= link_to t('orders.view'), order_path(o)
%br
.container
  .row
    .col-md-12
    %h4
      = t('orders.delivered')
    %table.table.table-hover
      %thead
        %tr
          %th.text-center= t('orders.number')
          %th.text-center= t('orders.completed_at')
          %th.text-center= t('orders.total')
          %th
      - @orders.delivered.each do |o|
        %tr.text-center
          %td= "№#{o.id}"
          %td= o.completed_date.strftime('%Y-%m-%d')
          %td= number_to_currency o.total_price
          %td= link_to t('orders.view'), order_path(o)

app/views/orders/payment.html.haml
.container
  .row
    .col-md-4
      = simple_form_for @credit_card, url: order_create_payment_path, method: :post do |f|
        = f.input :number
        %br
          = select_month(Date.today, use_month_numbers: true, prefix: 'credit_card', field_name: 'expiration_month')
          = select_year(Date.today, start_year: 2016, end_year: 2033, prefix: 'credit_card', field_name: 'expiration_year')
        %br
        = f.input :cvv
        %br= f.submit t("orders.save")
    .col-md-4
    .col-md-4

app/views/orders/show.html.haml
= render 'checkouts/order_show'