config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }
  resource :customer, only: [:edit, :update] do
    patch 'update_addresses'
  end

  root 'books#bestsellers'
  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  resources :categories, only: [:index, :show]
  resources :authors, only: [:show]

  resource :cart, only: [:show, :update] do
    post    'add_item'
    delete  'remove_item'
    post    'checkout'
    delete  'clear'
  end

  resources :orders, only: [:index, :show] do
    resource :checkout, only: [:show] do
      get   'addresses'
      patch 'update_addresses'
      get   'delivery'
      patch 'update_delivery'
      get   'payment'
      patch 'update_payment'
      get   'confirm'
      post  'place'
    end
  end

end

app/models/cart.rb
class Cart
  attr_accessor :session
  attr_reader :discount

  def initialize(session, discount=nil)
    @session = session
    @discount = discount
  end

  def remove_item_from_cart(item_id)
    @session.delete(item_id)
  end

  def params_valid?(params)
    params[:book_id].to_i.between?(1, Book.last.id) && params[:quantity].to_i.between?(1, 9)
  end

  def add_item_to_cart(cart_params)
    if params_valid?(cart_params)
      if @session.key?(cart_params[:book_id])
        @session[cart_params[:book_id]] += cart_params[:quantity].to_i
      else
        @session[cart_params[:book_id]] = cart_params[:quantity].to_i
      end
    end
  end

  def update_cart(params)
    @session.each_key { |k| @session[k] = params[k].to_i if params[k].to_i.between?(1, 9) }
    coupon_discount(params[:coupon]) || @discount
  end

  def coupon_discount(params)
    coupon = Coupon.find_by_code(params)
    coupon.discount unless coupon.blank?
  end

  def build_order_items_from_cart
    return if @session.empty?
    order_items = []
    @session.each do |k, v|
      order_items << OrderItem.new(book_id: k,
                                   price: Book.find(k).price * v,
                                   quantity: v)
    end
    order_items
  end

  def build_order(customer)
    return if @session.empty?
    order_items = build_order_items_from_cart
    order = customer.orders.new(total_price: subtotal, completed_date: Time.now)
    order.order_items << order_items
    order
  end

  def subtotal
    subtotal = 0
    @session.each_pair do |key, value|
      subtotal += Book.find(key).price * value
    end
    @discount ? subtotal * @discount : subtotal
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_customer!, only: [:checkout]
  load_and_authorize_resource

  def show
    @cart = cart.session
    @subtotal = cart.subtotal
  end

  def update
    session[:discount] = cart.update_cart(params)
    redirect_to cart_path
  end

  def add_item
    cart.add_item_to_cart(cart_params)
    redirect_to cart_path
  end

  def remove_item
    cart.remove_item_from_cart(params[:item_id])
    redirect_to cart_path
  end

  def clear
    clear_session
    redirect_to cart_path
  end

  def checkout
    @order = cart.build_order(current_customer)
    if !cart.session.empty? && @order.save
      clear_session
      redirect_to addresses_order_checkout_path(@order)
    else
      redirect_to cart_path
    end
  end

  private

  def clear_session
    session[:cart] = nil
    session[:discount] = nil
  end

  def cart
    Cart.new(session[:cart] ||= {}, session[:discount] ||= 1)
  end

  def cart_params
    params.require(:book).permit(:book_id, :quantity)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def order_item_book(book_id)
    Book.find_by_id(book_id)
  end

  def order_item_price(qty, book_id)
    qty * order_item_book(book_id).price
  end

  def total_items_quantity
    session[:cart].each_value.reduce(:+)
  end

  def cart_count
    session[:cart].blank? ? "EMPTY" : total_items_quantity
  end
end

app/views/carts/_add_to_cart.html.haml
%h4.form-inline.pull-right
  = simple_form_for book, url: add_item_cart_path, method: :post do |f|
    = number_to_currency book.price
    = f.input :quantity, class: "form-control",
      input_html: { value: 1, min: '1', max: 9, type: 'number'}, label: false
    = f.hidden_field :book_id, value: book.id
    = f.button :submit, t('books.add_to_cart'), class: "btn btn-primary"

app/views/carts/index.html.haml
- if @cart.blank?
  = t('cart.your_cart_empty')
- @cart.each_pair do |book_id, qty|
  %br
    = "Book: #{order_item_book(book_id).title},
      Quantity: #{qty},
      Price: #{order_item_price(qty, book_id)}"
    = link_to('x', remove_item_carts_path(item_id: book_id), method: :delete)
- unless @cart.empty?
  %br= t("cart.subtotal") + " #{number_to_currency @subtotal}"
  = link_to(t('cart.empty_cart'), clear_carts_path, method: :delete)
  %br
  %br= link_to("CHECKOUT", orders_path, method: :post)

app/views/carts/show.html.haml
.container
  .row
    - if @cart.blank?
      .text-center.jumbotron.lead
        = t('cart.your_cart_empty')
    - else
      = form_tag(cart_path, method: :patch) do
        %table.table.table-hover.cart
          %thead
            %tr
              %th
              %th= t('cart.book')
              %th.text-center= t('cart.price')
              %th.text-center= t('cart.qty')
              %th.text-center= t('cart.total')
              %th
          - @cart.each_pair do |book_id, qty|
            %tr
              %td= image_tag(order_item_book(book_id).book_cover, size: "50x82")
              %td
                %dl
                  %dt= order_item_book(book_id).title
                  %dd= truncate(order_item_book(book_id).description, length: 250)
              %td.text-center.cart_price= number_to_currency order_item_book(book_id).price
              %td.text-center.cart-qty{id: "qty_#{book_id}"}= number_field_tag book_id, qty,class: 'form-control', min: '1', max: '9'
              %td.text-center.cart_total= number_to_currency order_item_price(qty, book_id)
              %td.text-center.cart_remove= link_to('×', remove_item_cart_path(item_id: book_id), method: :delete, class: 'close', id: book_id)
        - unless @cart.empty?
          %p.text-right
            %strong.subtotal= t('cart.subtotal') + " #{number_to_currency @subtotal}"
          .col-md-4
            = link_to t('cart.empty_cart'), clear_cart_path, method: :delete, class: 'btn btn-danger'
            = link_to t('cart.continue_shoping'), books_path, class: 'btn btn-default'
          .col-md-6
            .form-inline.text-right
              .form-group
                = text_field_tag :coupon, nil, {class: 'form-control', id: 'coupon', placeholder: t('cart.coupon_code') + ' (1111 -20%)'}
              .form-group
                = submit_tag t('cart.update'), class: 'btn btn-primary btn-block'
          .col-md-2.text-right
            = link_to t('cart.checkout'), checkout_cart_path, method: :post, class: 'btn btn-success'