config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }
  resource :customer, only: [:edit, :update] do
    patch 'update_addresses'
  end

  root 'books#bestsellers'
  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  resources :categories, only: [:index, :show]
  resources :authors, only: [:show]

  resource :cart, only: [:show, :update] do
    post    'add_item'
    delete  'remove_item'
    post    'checkout'
    delete  'clear'
  end

  resources :orders, only: [:index, :show] do
    resource :checkout, only: [:show] do
      get   'addresses'
      patch 'update_addresses'
      get   'delivery'
      patch 'update_delivery'
      get   'payment'
      patch 'update_payment'
      get   'confirm'
      post  'place'
    end
  end

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_customer!
  load_and_authorize_resource :order
  before_action :set_customer
  before_action :order_state_check, except: [:show]
  before_action :addresses_init, only: [:addresses, :update_addresses]
  before_action :find_or_init_credit_card, only: [:payment, :update_payment]

  def addresses
  end

  def update_addresses
    _shipping_params = params[:shipping_as_billing] ? billing_params : shipping_params
    if @billing_address.update(billing_params) && @shipping_address.update(_shipping_params)
      redirect_to delivery_order_checkout_path
    else
      render 'addresses'
    end
  end

  def delivery
    if @order.billing_address.nil? || @order.shipping_address.nil?
      redirect_to addresses_order_checkout_path
    else
      @deliveries = Delivery.all
    end
  end

  def update_delivery
    if Delivery.find(delivery_params[:delivery_id])
      @order.update(delivery_params)
      redirect_to payment_order_checkout_path
    end
  end

  def payment
    redirect_to delivery_order_checkout_path if @order.delivery.nil?
  end

  def update_payment
    if @credit_card.update(payment_params)
      redirect_to confirm_order_checkout_path
    else
      render 'payment'
    end
  end

  def confirm
    redirect_to payment_order_checkout_path if @order.credit_card.nil?
  end

  def place
    if @order.place!
      redirect_to order_checkout_path
    else
      render 'confirm'
    end
  end

  def show
    redirect_to confirm_order_checkout_path unless @order.in_queue?
  end

  private

  def find_or_init_credit_card
    @credit_card = CreditCard.find_or_initialize_by(order_id: @order.id)
  end

  def order_state_check
    redirect_to root_path unless @order.in_progress?
  end

  def addresses_init
    @countries = Country.all
    if @order.shipping_address.nil? || @order.billing_address.nil?
      @billing_address = BillingAddress.build_order_address(@customer, @order)
      @shipping_address = ShippingAddress.build_order_address(@customer, @order)
    else
      @billing_address = BillingAddress.find_or_initialize_by(order_id: @order.id)
      @shipping_address = ShippingAddress.find_or_initialize_by(order_id: @order.id)
    end
  end

  def billing_params
    params.require(:billing_address).permit(:firstname, :lastname,
                                            :address, :city, :country_id,
                                            :country, :zipcode, :phone)
  end

  def shipping_params
    params.require(:shipping_address).permit(:firstname, :lastname,
                                             :address, :city, :country_id,
                                             :country, :zipcode, :phone)
  end

  def delivery_params
    params.fetch(:order, {}).permit(:delivery_id)
  end

  def payment_params
    params.require(:credit_card).permit(:expiration_month, :number,
                                        :expiration_year, :cvv)
  end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/_checkout_header.html.haml
.container
  .row
    .col-md-12
      %h3= t('checkout.checkout')
      %ol.breadcrumb.text-center
        %li
          = link_to t('checkout.address'), addresses_order_checkout_path
        %li.text-uppercase
          - if @order.billing_address.nil? || @order.shipping_address.nil?
            = t('checkout.delivery')
          - else
            = link_to t('checkout.delivery'), delivery_order_checkout_path
        %li.text-uppercase
          - if @order.delivery.nil?
            = t('checkout.payment')
          - else
            = link_to t('checkout.payment'), payment_order_checkout_path
        %li
          - if @order.credit_card.nil?
            = t('checkout.confirm')
          - else
            = link_to t('checkout.confirm'), confirm_order_checkout_path
        %li
          = t('checkout.complete')

app/views/checkouts/_order_show.html.haml
.container
  .row
    .col-md-12
      %h4.well.well-sm
        = "#{t('checkout.order')}#{@order.id}"
        %small= @order.state.humanize
.container
  .row
    .col-md-3
      %h5
        %strong= t('checkout.billing_address')
      %ul.list-unstyled
        %li="#{@order.billing_address.firstname} #{@order.billing_address.lastname}"
        %li="#{@order.billing_address.address}"
        %li="#{@order.billing_address.city} #{@order.billing_address.zipcode}"
        %li="#{@order.billing_address.country.name}"
        %li="#{@order.billing_address.phone}"
    .col-md-3
      %h5
        %strong= t('checkout.shipping_address')
      %ul.list-unstyled
        %li="#{@order.shipping_address.firstname} #{@order.shipping_address.lastname}"
        %li="#{@order.shipping_address.address}"
        %li="#{@order.shipping_address.city} #{@order.shipping_address.zipcode}"
        %li="#{@order.shipping_address.country.name}"
        %li="#{@order.shipping_address.phone}"
    .col-md-3
      %h5
        %strong= t('checkout.shipments')
      %ul.list-unstyled
        %li= @order.delivery.title
        %li= number_to_currency @order.delivery.price
    .col-md-3
      %h5
        %strong= t('checkout.payment_information')
      %ul.list-unstyled
        %li= "#{t('checkout.asterisk')} #{@order.credit_card.number.to_s.last(4)}"
        %li= "#{@order.credit_card.expiration_month} / #{@order.credit_card.expiration_year}"
.container
  .row
    .col-md-12
      %table.table.table-hover
        %thead
          %tr
            %th
            %th= t('checkout.book')
            %th.text-center= t('checkout.price')
            %th.text-center= t('checkout.qty')
            %th.text-center= t('checkout.total')
            %th
        - @order.order_items.each do |oi|
          %tr
            %td= image_tag(oi.book.book_cover, size: "50x82")
            %td
              %dl
                %dt= oi.book.title
                %dd= truncate(oi.book.description, length: 250)
            %td.text-center= number_to_currency oi.price
            %td.text-center= oi.quantity
            %td.text-center= number_to_currency oi.price
.container
  .row
    .col-md-9
    .col-md-3
      %table.table.table-hover
        %thead
          %tr
            %td
              %ul.list-unstyled.text-right
                %li= t('checkout.subtotal')
                %li= t('checkout.shipping')
            %td
              %ul.list-unstyled
                %li= number_to_currency @order.total_price - @order.delivery.price
                %li= number_to_currency @order.delivery.price
          %tr
            %td
              %ul.list-unstyled.text-right
                %li
                  %strong= t('checkout.order_total')
            %td
              %ul.list-unstyled
                %li
                  %strong= number_to_currency @order.total_price
.container
  .row
    .col-md-12
      %br= link_to t('checkout.back_to_store'), root_path, class: 'btn btn-default'

app/views/checkouts/_order_summary.html.haml
.panel.panel-default.shipping
  .panel-heading
    %h4
      = t('checkout.order_summary')
  .panel-body
    %table.table
      %thead
        %tr
          %td= t('checkout.item_total')
          %td= number_to_currency @order.total_price
        %tr
          %td= t('checkout.shipping')
          %td
            - if @order.delivery.blank?
              = number_to_currency @deliveries.first.price
            - else
              = number_to_currency @order.delivery.price
        %tr.info
          %td= t('checkout.order_total')
          %td
            - if @order.delivery.blank?
              = number_to_currency @order.total_price + @deliveries.first.price
            - else
              = number_to_currency @order.total_price + @order.delivery.price

app/views/checkouts/addresses.html.haml
= render 'checkout_header'
.container
  .row
    = simple_form_for(:addresses, url: update_addresses_order_checkout_path, :method => :patch) do |a|
      .col-md-4
        .panel.panel-default.billing
          .panel-heading
            %h4= t('checkout.billing_address', :default => "Billing Address")
          .panel-body
            = simple_fields_for @billing_address do |ba|
              = ba.input :firstname
              = ba.input :lastname
              = ba.input :address
              = ba.input :city
              = ba.input :country_id, collection: @countries
              = ba.input :zipcode
              = ba.input :phone, as: 'tel'
      .col-md-4
        .panel.panel-default.shipping
          .panel-heading
            %h4
              = t('checkout.shipping_address', :default => "Shipping Address")
              = check_box_tag 'shipping_as_billing', true, false, id: 'shipping-checkbox'
              %em.small Use Billing Address
          .panel-body.shipping-input
            = simple_fields_for @shipping_address do |sa|
              = sa.input :firstname
              = sa.input :lastname
              = sa.input :address
              = sa.input :city
              = sa.input :country_id, collection: @countries
              = sa.input :zipcode
              = sa.input :phone, as: 'tel'
      .col-md-4
        .panel.panel-default.shipping
          .panel-heading
            %h4
              = t('checkout.order_summary')
          .panel-body
            %table.table
              %thead
                %tr
                  %td= t('checkout.item_total')
                  %td= number_to_currency @order.total_price
                %tr
                  %td
                    %br
                  %td
                %tr.info
                  %td= t('checkout.order_total')
                  %td= number_to_currency @order.total_price
      .col-md-12
        %br= a.submit t("checkout.save"), class: 'btn btn-primary'

app/views/checkouts/confirm.html.haml
= render 'checkout_header'
.container
  .row
    .col-md-12
      %h4= t('checkout.confirm')
.container
  .row
    .col-md-3
      %h5
        %strong= t('checkout.billing_address')
        %small= link_to(t('checkout.edit'), addresses_order_checkout_path)
      %ul.list-unstyled
        %li="#{@order.billing_address.firstname} #{@order.billing_address.lastname}"
        %li="#{@order.billing_address.address}"
        %li="#{@order.billing_address.city} #{@order.billing_address.zipcode}"
        %li="#{@order.billing_address.country.name}"
        %li="#{@order.billing_address.phone}"
    .col-md-3
      %h5
        %strong= t('checkout.shipping_address')
        %small= link_to(t('checkout.edit'), addresses_order_checkout_path)
      %ul.list-unstyled
        %li="#{@order.shipping_address.firstname} #{@order.shipping_address.lastname}"
        %li="#{@order.shipping_address.address}"
        %li="#{@order.shipping_address.city} #{@order.shipping_address.zipcode}"
        %li="#{@order.shipping_address.country.name}"
        %li="#{@order.shipping_address.phone}"
    .col-md-3
      %h5
        %strong= t('checkout.shipments')
        %small= link_to(t('checkout.edit'), delivery_order_checkout_path)
      %ul.list-unstyled
        %li= @order.delivery.title
        %li= number_to_currency @order.delivery.price
    .col-md-3
      %h5
        %strong= t('checkout.payment_information')
        %small= link_to(t('checkout.edit'), payment_order_checkout_path)
      %ul.list-unstyled
        %li= "#{t('checkout.asterisk')} #{@order.credit_card.number.to_s.last(4)}"
        %li= "#{@order.credit_card.expiration_month} / #{@order.credit_card.expiration_year}"
.container
  .row
    .col-md-12
      %table.table.table-hover
        %thead
          %tr
            %th
            %th= t('checkout.book')
            %th.text-center= t('checkout.price')
            %th.text-center= t('checkout.qty')
            %th.text-center= t('checkout.total')
            %th
        - @order.order_items.each do |oi|
          %tr
            %td= image_tag(oi.book.book_cover, size: "50x82")
            %td
              %dl
                %dt= oi.book.title
                %dd= truncate(oi.book.description, length: 250)
            %td.text-center= number_to_currency oi.price
            %td.text-center= oi.quantity
            %td.text-center= number_to_currency oi.price
.container
  .row
    .col-md-9
    .col-md-3
      %table.table.table-hover
        %thead
          %tr
            %td
              %ul.list-unstyled.text-right
                %li= t('checkout.subtotal')
                %li= t('checkout.shipping')
            %td
              %ul.list-unstyled
                %li= number_to_currency @order.total_price
                %li= number_to_currency @order.delivery.price
          %tr
            %td
              %ul.list-unstyled.text-right
                %li
                  %strong= t('checkout.order_total')
            %td
              %ul.list-unstyled
                %li
                  %strong= number_to_currency @order.total_price + @order.delivery.price
.container
  .row
    .col-md-12
      %br= button_to t('checkout.place_order'), place_order_checkout_path, method: :post, class: 'btn btn-success'

app/views/checkouts/delivery.html.haml
= render 'checkout_header'
.container
  .row
    .col-md-4
      .panel.panel-default.billing
        .panel-heading
          %h4.text-capitalize= t('checkout.delivery')
        .panel-body
          = simple_form_for @order, url: update_delivery_order_checkout_path(@order), method: :patch do |f|
            - @deliveries.each do |d|
              .radid
                %lable
                  %p
                    = f.radio_button :delivery_id, d.id, checked: d == @order.delivery || d == @deliveries.first
                    = "#{d.title} + #{number_to_currency(d.price)}"
            %br= f.submit t("checkout.save"), class: 'btn btn-primary'
    .col-md-4
    .col-md-4
      = render 'order_summary'

app/views/checkouts/payment.html.haml
= render 'checkout_header'
.container
  .row
    .col-md-4
      .panel.panel-default.billing
        .panel-heading
          %h4.text-capitalize= t('checkout.payment')
        .panel-body
          = simple_form_for @credit_card, url: update_payment_order_checkout_path, method: :patch do |f|
            = f.input :number, label: false, placeholder: 'Card Number', input_html: { minlength: 16, maxlength: 16 }
            %br
              %h5= t('checkout.expiration_date')
              = select_month(Date.today, use_month_numbers: true, prefix: 'credit_card', field_name: 'expiration_month')
              = select_year(Date.today, start_year: 2016, end_year: 2033, prefix: 'credit_card', field_name: 'expiration_year')
            %br
            .form-inline
              = f.input :cvv, label: false, placeholder: 'CVV', input_html: { minlength: 3, maxlength: 3, style: 'width: 80px' }
              = link_to t('checkout.whats_this'), 'https://www.cvvnumber.com/'
            %br= f.submit t("checkout.save"), class: 'btn btn-primary'
    .col-md-4
    .col-md-4
      = render 'order_summary'

app/views/checkouts/show.html.haml
= render 'order_show'