config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }
  resource :customer, only: [:edit, :update] do
    patch 'update_addresses'
  end

  root 'books#bestsellers'
  resources :books, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
  resources :categories, only: [:index, :show]
  resources :authors, only: [:show]

  resource :cart, only: [:show, :update] do
    post    'add_item'
    delete  'remove_item'
    post    'checkout'
    delete  'clear'
  end

  resources :orders, only: [:index, :show] do
    resource :checkout, only: [:show] do
      get   'addresses'
      patch 'update_addresses'
      get   'delivery'
      patch 'update_delivery'
      get   'payment'
      patch 'update_payment'
      get   'confirm'
      post  'place'
    end
  end

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-static-top
  .container
    .row
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false","data-target" => ".collapse.navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.glyphicon.glyphicon-menu-hamburger
        .navbar-brand The Bookstore
      .collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li
            %a{:href => "/"}= t('header.home')
          %li
            %a{:href => "/books"}= t('header.shop')
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to(cart_path) do
              %span.glyphicon.glyphicon-shopping-cart
              = t('header.cart') + " (#{cart_count})"
          - if customer_signed_in?
            %li
              = link_to(t('header.orders'), orders_path)
            %li
              = link_to(t('header.settings'), edit_customer_path)
            %li
              = link_to(t('header.sign_out'), destroy_customer_session_path, :method => :delete, class: "btn btn-default navbar-btn")
          - else
            %li
              = link_to(t('header.sign_up'), new_customer_registration_path, class: "btn btn-success navbar-btn")
            %li
              = link_to(t('header.sign_in'), new_customer_session_path, class: "btn btn-default navbar-btn")

app/views/layouts/_messages.html.haml
.container.messages
  .row
    .col-md-4
    .col-md-4
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key} alert-dismissible"}
          %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} &times;
          = value
    .col-md-4

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title TheBookstore
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    = yield